import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Navigation, Pagination, Autoplay, EffectCoverflow } from 'swiper'
import 'swiper/css'
import 'swiper/css/navigation'
import "swiper/css/effect-coverflow";
import 'swiper/css/pagination';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Swiper
        // pagination={{
        //   type: "progressbar",
        // }}
        effect={"coverflow"}
        grabCursor={true}
        centeredSlides={true}
        slidesPerView={"auto"}
        coverflowEffect={{
          rotate: 50,
          stretch: 0,
          depth: 100,
          modifier: 1,
          slideShadows: true,
        }}
        autoplay={{
          delay: 3000,
          disableOnInteraction: false,
        }}
        // navigation={
        //   true
        // }
        modules={[Pagination, Navigation, Autoplay,EffectCoverflow ]}
        className={styles.mySwiper}
      >
        <SwiperSlide className={styles.swiper_slide}>
          <img src="https://bizflyportal.mediacdn.vn/bizflyportal/1570/2428/2021/06/22/20/40/ban16243476131389.jpg" alt="" />
        </SwiperSlide>
        <SwiperSlide className={styles.swiper_slide}>
          <img src="https://bizflyportal.mediacdn.vn/bizflyportal/1570/2428/2021/06/22/20/40/ban16243476131389.jpg" alt="" />
        </SwiperSlide>
        <SwiperSlide className={styles.swiper_slide}>
          <img src="https://bizflyportal.mediacdn.vn/bizflyportal/1570/2428/2021/06/22/20/40/ban16243476131389.jpg" alt="" />
        </SwiperSlide>
      </Swiper>

      <iframe width="420" height="345"
        src="https://www.youtube.com/embed/tgbNymZ7vqY?autoplay=1&mute=1">
      </iframe>

      <video className={styles.video} width={320} height={240} controls>
        <source src="movie.mp4" type="video/mp4" />
        <source src="movie.ogg" type="video/ogg" />
        Your browser does not support the video tag.
      </video>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>test vercel</h1>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
